# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# S131 W2 (TD-026 cont. full wire-up): переписываем import на absolute.
# Default protoc (v1.71+) генерит ``import files_pb2 as files__pb2`` (relative),
# что требует наличия ``src/backend/entrypoints/grpc/protobuf/`` в sys.path
# при импорте servicer'а. Existing ``orders_pb2_grpc.py`` / ``invoker_pb2_grpc.py``
# (W1.3 era) используют absolute import — соблюдаем тот же стиль для
# consistency + lazy import-безопасности (servicer может быть imported до
# того, как sys.path настроен).
import src.backend.entrypoints.grpc.protobuf.files_pb2 as files__pb2  # noqa: I001

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in files_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFile = channel.unary_unary(
                '/files.FileService/GetFile',
                request_serializer=files__pb2.GetFileRequest.SerializeToString,
                response_deserializer=files__pb2.FileResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/files.FileService/DeleteFile',
                request_serializer=files__pb2.GetFileRequest.SerializeToString,
                response_deserializer=files__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/files.FileService/DownloadFile',
                request_serializer=files__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=files__pb2.FileChunk.FromString,
                _registered_method=True)
        self.UploadFile = channel.stream_unary(
                '/files.FileService/UploadFile',
                request_serializer=files__pb2.FileUploadRequest.SerializeToString,
                response_deserializer=files__pb2.FileUploadResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """S128 W3 (TD-026): server streaming для больших файлов.
        Server → client chunks (по 64KB default). Без memory-pressure на стороне сервера.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """S128 W3 (TD-026): client streaming для загрузки.
        Client → server chunks. Server accumulates → storage backend.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=files__pb2.GetFileRequest.FromString,
                    response_serializer=files__pb2.FileResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=files__pb2.GetFileRequest.FromString,
                    response_serializer=files__pb2.DeleteResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=files__pb2.DownloadFileRequest.FromString,
                    response_serializer=files__pb2.FileChunk.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=files__pb2.FileUploadRequest.FromString,
                    response_serializer=files__pb2.FileUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'files.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('files.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/files.FileService/GetFile',
            files__pb2.GetFileRequest.SerializeToString,
            files__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/files.FileService/DeleteFile',
            files__pb2.GetFileRequest.SerializeToString,
            files__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/files.FileService/DownloadFile',
            files__pb2.DownloadFileRequest.SerializeToString,
            files__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/files.FileService/UploadFile',
            files__pb2.FileUploadRequest.SerializeToString,
            files__pb2.FileUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
