# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: files.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'files.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66iles.proto\x12\x05\x66iles\"!\n\x0eGetFileRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x05\"L\n\x0c\x46ileResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bobject_uuid\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"0\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"6\n\x13\x44ownloadFileRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x03\"W\n\tFileChunk\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x19\n\x11\x66inal_fingerprint\x18\x03 \x01(\t\x12\x0f\n\x07is_last\x18\x04 \x01(\x08\"g\n\x11\x46ileUploadRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x0f\n\x07is_last\x18\x05 \x01(\x08\"r\n\x12\x46ileUploadResponse\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x05\x12\x13\n\x0bobject_uuid\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x03\x12\x13\n\x0b\x66ingerprint\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t2\x8d\x02\n\x0b\x46ileService\x12\x37\n\x07GetFile\x12\x15.files.GetFileRequest\x1a\x13.files.FileResponse\"\x00\x12<\n\nDeleteFile\x12\x15.files.GetFileRequest\x1a\x15.files.DeleteResponse\"\x00\x12@\n\x0c\x44ownloadFile\x12\x1a.files.DownloadFileRequest\x1a\x10.files.FileChunk\"\x00\x30\x01\x12\x45\n\nUploadFile\x12\x18.files.FileUploadRequest\x1a\x19.files.FileUploadResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'files_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETFILEREQUEST']._serialized_start=22
  _globals['_GETFILEREQUEST']._serialized_end=55
  _globals['_FILERESPONSE']._serialized_start=57
  _globals['_FILERESPONSE']._serialized_end=133
  _globals['_DELETERESPONSE']._serialized_start=135
  _globals['_DELETERESPONSE']._serialized_end=183
  _globals['_DOWNLOADFILEREQUEST']._serialized_start=185
  _globals['_DOWNLOADFILEREQUEST']._serialized_end=239
  _globals['_FILECHUNK']._serialized_start=241
  _globals['_FILECHUNK']._serialized_end=328
  _globals['_FILEUPLOADREQUEST']._serialized_start=330
  _globals['_FILEUPLOADREQUEST']._serialized_end=433
  _globals['_FILEUPLOADRESPONSE']._serialized_start=435
  _globals['_FILEUPLOADRESPONSE']._serialized_end=549
  _globals['_FILESERVICE']._serialized_start=552
  _globals['_FILESERVICE']._serialized_end=821
# @@protoc_insertion_point(module_scope)
