# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import invoker_pb2 as invoker__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in invoker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InvokerServiceStub(object):
    """Universal Invoker gRPC service (W22 этап B).
    Дублирует REST/SOAP/WS-точки входа: один rpc Invoke на все
    шесть InvocationMode (sync / async-api / async-queue / deferred /
    background / streaming).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/invoker.InvokerService/Invoke',
                request_serializer=invoker__pb2.InvokeRequest.SerializeToString,
                response_deserializer=invoker__pb2.InvokeResponse.FromString,
                _registered_method=True)


class InvokerServiceServicer(object):
    """Universal Invoker gRPC service (W22 этап B).
    Дублирует REST/SOAP/WS-точки входа: один rpc Invoke на все
    шесть InvocationMode (sync / async-api / async-queue / deferred /
    background / streaming).
    """

    def Invoke(self, request, context):
        """Универсальный вход: sync, async-api, async-queue, deferred,
        background. Streaming-режим возвращает ACCEPTED, чанки доставляются
        через reply_channel (ws/queue/email/express).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InvokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=invoker__pb2.InvokeRequest.FromString,
                    response_serializer=invoker__pb2.InvokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'invoker.InvokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('invoker.InvokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InvokerService(object):
    """Universal Invoker gRPC service (W22 этап B).
    Дублирует REST/SOAP/WS-точки входа: один rpc Invoke на все
    шесть InvocationMode (sync / async-api / async-queue / deferred /
    background / streaming).
    """

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/invoker.InvokerService/Invoke',
            invoker__pb2.InvokeRequest.SerializeToString,
            invoker__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
