# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: invoker.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'invoker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinvoker.proto\x12\x07invoker\"\x88\x01\n\rInvokeRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\x15\n\rreply_channel\x18\x04 \x01(\t\x12\x15\n\rinvocation_id\x18\x05 \x01(\t\x12\x15\n\rmetadata_json\x18\x06 \x01(\t\"i\n\x0eInvokeResponse\x12\x15\n\rinvocation_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\x13\n\x0bresult_json\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t2M\n\x0eInvokerService\x12;\n\x06Invoke\x12\x16.invoker.InvokeRequest\x1a\x17.invoker.InvokeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invoker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOKEREQUEST']._serialized_start=27
  _globals['_INVOKEREQUEST']._serialized_end=163
  _globals['_INVOKERESPONSE']._serialized_start=165
  _globals['_INVOKERESPONSE']._serialized_end=270
  _globals['_INVOKERSERVICE']._serialized_start=272
  _globals['_INVOKERSERVICE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
