app:
  base_url: "localhost:8000"
  environment: "development"
  debug_mode: false
  version: 0.1.0

auth:
  token_name: "gat_token"
  token_lifetime: 120
  refresh_token_lifetime: 4800
  algorithm: "HS256"
  cookie_secure: True
  cookie_samesite: "lax"
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
  routes_without_api_key:
    - "/"
    - "/admin"
    - "/admin/*"
    - "/docs"
    - "/documents"
    - "/docs/"
    - "/documents/"
    - "/metrics"
    - "/openapi.json"
    - "/tech/healthcheck-*"
    - "/tech/redirect-*"
    - "/tech/version"
    - "/tech/log-storage"
    - "/tech/file-storage"
    - "/tech/task-monitor"
  request_timeout: 20.0
  rate_limit: 400
  rate_time_measure_seconds: 60

http:
  max_retries: 3
  retry_backoff_factor: 0.5
  retry_status_codes:
    - 408
    - 429
    - 500
    - 502
    - 503
    - 504
  total_timeout: 30
  connect_timeout: 10
  sock_read_timeout: 15
  keepalive_timeout: 300
  limit: 100
  limit_per_host: 20
  ttl_dns_cache: 300
  force_close: False

skb:
  base_url: "https://api.skb-techno.ru/v2/Requests/"
  endpoints:
    GET_KINDS: "Kinds"
    CREATE_REQUEST: "Create"
    GET_RESULT: "Result"
  default_priority: 80
  connect_timeout: 10.0
  read_timeout: 30.0

dadata:
  base_url: "https://suggestions.dadata.ru/suggestions/api/4_1/rs/"
  endpoints:
    GEOLOCATE: "geolocate/address"
  geolocate_radius_default: 100
  connect_timeout: 15.0
  read_timeout: 40.0

database:
  type: "postgresql"
  host: "localhost"
  port: 5432
  name: "postgres"
  async_driver: "asyncpg"
  sync_driver: "psycopg2"
  echo: True
  connect_timeout: 10
  command_timeout: 30
  pool_size: 10
  max_overflow: 10
  pool_recycle: 1800
  pool_timeout: 30
  ssl_mode: prefer
  ca_bundle: #"/path/to/certificate.pem"

fs:
  provider: "minio"
  bucket: "test-bucket"
  endpoint: "http://127.0.0.1:9090"
  interface_endpoint: "http://127.0.0.1:9091"
  use_ssl: False
  verify: False
  ca_bundle: #"/path/to/certificate.pem"
  timeout: 30
  retries: 5
  key_prefix: "uploads"

log:
  host: "localhost"
  port: 9000
  udp_port: 12201
  conf_loggers: 
    - name: "application"
      facility: "application"
    - name: "database"
      facility: "database"
    - name: "storage"
      facility: "storage"
    - name: "smtp"
      facility: "smtp"
    - name: "scheduler"
      facility: "scheduler"
    - name: "request"
      facility: "request"
    - name: "queue"
      facility: "queue"
    - name: "redis"
      facility: "redis"
  use_tls: False
  ca_bundle: #"/path/to/certificate.pem"
  level: "DEBUG"
  name_log_file: "app.log"
  dir_log_name: "logs"
  required_fields:
    - "environment"
    - "hostname"
    - "user_id"
    - "action"

redis:
  host: "localhost"
  port: 6379
  db_cache: 0
  db_queue: 1
  db_limits: 2
  db_celery: 3
  encoding: "utf-8"
  cache_expire_seconds: 300
  max_connections: 20
  use_ssl: False
  ca_bundle: #"/path/to/certificate.pem"
  socket_timeout: 600
  socket_connect_timeout: 10
  retry_on_timeout: True
  socket_keepalive: True

celery:
  redis_db: 3
  task_default_queue: "default"
  task_serializer: "json"
  task_time_limit: 6000
  task_soft_time_limit: 300
  task_max_retries: 10
  task_min_retries: 3
  task_default_retry_delay: 3
  task_retry_backoff: 60
  task_retry_jitter: True
  countdown_time: 60
  worker_concurrency: 5
  worker_prefetch_multiplier: 5
  worker_max_tasks_per_child: 500
  worker_disable_rate_limits: False
  flower_url: "http://localhost:8888"
  flower_basic_auth: 
  task_track_started: True
  broker_pool_limit: 20
  result_extended: True
  worker_send_events: True

mail:
  host: "localhost"
  port: 1025
  connection_pool_size: 10
  command_timeout: 30
  connect_timeout: 10
  circuit_breaker_timeout: 10
  sender: "gd_advanced_tools@app.com"
  use_tls: False
  validate_certs: False
  ca_bundle: #"/path/to/certificate.pem"
  template_folder: 

queue:
  type: "kafka"
  bootstrap_servers:
    - "localhost:9092"
  consumer_group: "api-consumers"
  auto_offset_reset: "earliest"
  max_poll_records: 500
  dlq_suffix: "_dlq"
  max_processing_attempts: 3
  producer_acks: "all"
  producer_linger_ms: 5
  security_protocol: "PLAINTEXT"
  ca_bundle: #"/path/to/certificate.pem"
  compression_type: "lz4"
  message_max_bytes: 1048576
  session_timeout_ms: 10000
  request_timeout_ms: 40000
  max_in_flight_requests: 5