[tool.poetry]
name = "gd-advanced-tools"
version = "0.1.0"
description = ""
authors = ["crazyivan1289 <crazyivan1289@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.2"
sqlalchemy = "^2.0.36"
uvicorn = {extras = ["standart"], version = "^0.32.0"}
pydantic = "^2.9.2"
pydantic-settings = "^2.6.0"
fastapi-utils = "^0.7.0"
asyncpg = "^0.29.0"
alembic = "^1.13.3"
greenlet = "^3.1.1"
python-dotenv = "^1.0.1"
httpx = "^0.27.2"
bump-pydantic = "^0.8.0"
typing-inspect = "^0.9.0"
celery = "^5.4.0"
flower = "^2.0.1"
fastapi-filter = "^2.0.0"
aioboto3 = "^13.2.0"
python-multipart = "^0.0.17"
black = "^24.10.0"
flake8 = "^7.1.1"
mypy = "^1.13.0"
isort = "^5.13.2"
autopep8 = "^2.3.1"
pylint = "^3.3.1"
graypy = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
