[tool.poetry]
name = "gd_advanced_tools"
version = "0.1.0"
description = ""
authors = ["crazyivan1289 <crazyivan1289@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.2"
sqlalchemy = "^2.0.36"
uvicorn = {extras = ["standart"], version = "^0.32.0"}
pydantic = {extras = ["email"], version = "^2.10.3"}
pydantic-settings = "^2.6.0"
fastapi-utils = "^0.7.0"
asyncpg = "^0.29.0"
alembic = "^1.13.3"
greenlet = "^3.1.1"
python-dotenv = "^1.0.1"
bump-pydantic = "^0.8.0"
typing-inspect = "^0.9.0"
flower = "^2.0.1"
fastapi-filter = "^2.0.0"
aioboto3 = "^13.2.0"
python-multipart = "^0.0.17"
black = "^24.10.0"
flake8 = "^7.1.1"
mypy = "^1.13.0"
isort = "^5.13.2"
autopep8 = "^2.3.1"
pylint = "^3.3.1"
graypy = "^2.1.0"
sqladmin = "^0.20.1"
passlib = "^1.7.4"
setuptools = "^75.6.0"
aiohttp = "^3.11.10"
redis = "4.5.5"
poetry-dotenv-plugin = "^0.2.0"
websockets = "^14.1"
vine = "^5.1.0"
celery = "^5.4.0"
eventlet = "^0.38.2"
json-tricks = "^3.17.3"
aiosmtplib = "^3.0.2"
sqlalchemy-utils = "^0.41.2"
prometheus-fastapi-instrumentator = "^7.0.0"
starlette-exporter = "^0.23.0"
apscheduler = "^3.11.0"
pyclamd = "^0.4.0"
fastapi-limiter = "^0.1.6"
vulture = "^2.14"
pandas = "^2.2.3"
openpyxl = "^3.1.5"
sqlalchemy-continuum = "^1.4.2"
psycopg2 = "^2.9.10"
zeep = "^4.3.1"
bandit = "^1.8.2"
confluent-kafka = "^2.8.0"


[tool.poetry.group.dev.dependencies]
mypy = "^1.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ["py312"]
include = '\.pyi?$'
exclude = '/migrations/'

[tool.isort]
src_paths = ["./app"]
skip = ["__init__.py"]
combine_as_imports = true
balanced_wrapping = true
include_trailing_comma = true
multi_line_output = 3
lines_after_imports = 2
known_standard_library = [
    "hashlib", "re", "os", "path", "collections", "io", "enum", "sys",
    "traceback", "datetime", "typing", "contextlib", "functools",
    "logging", "pathlib", "abc", "uuid", "json", "importlib"
]
known_third_party = [
    "confluent_kafka", "aiologger", "aiokafka", "urllib", "zeep", "blinker",
    "pandas", "graypy", "pyclamd", "sqlalchemy_utils", "fastapi_limiter",
    "loguru", "sqlalchemy", "fast_api", "passlib", "aioredis", "asyncio",
    "pydantic", "sqladmin", "joblib", "streamlit", "aioboto", "fastauth",
    "tiny_url", "jose", "aiobotocore", "pyshorteners", "aiohttp", "celery",
    "redis", "flet", "apscheduler", "fastapi_utils"
]
known_first_party = ["app"]
no_lines_before = ["FUTURE", "STANDARD_LIBRARY", "THIRD_PARTY", "FIRST_PARTY", "LOCAL_FOLDER"]

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]
check_untyped_defs = true
disallow_incomplete_defs = true
disable_error_code = [
    "no-untyped-def",
    "override",
    "arg-type",
    "assignment",
    "import-untyped",
    "union-attr",
    "var-annotated"
]
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true

[tool.flake8]
ignore = "E501,W503"
exclude = [
    ".git", ".gitignore", "__pycache__", "*/migrations/*", "versions*",
    ".venv", ".pytest_cache", ".coverage", ".mypy_cache", "*env*", "*venv"
]
max-line-length = 97
max-complexity = 18
