"""DSL Processors — re-export для обратной совместимости.

Все процессоры доступны через:
    from src.backend.dsl.engine.processors import BaseProcessor, DispatchActionProcessor, ...
"""

from src.backend.dsl.engine.processors.ai import (
    CacheProcessor,
    CacheWriteProcessor,
    GetFeedbackExamplesProcessor,
    GuardrailsProcessor,
    LLMCallProcessor,
    LLMFallbackProcessor,
    LLMParserProcessor,
    PromptComposerProcessor,
    RagIngestProcessor,
    RagQueryProcessor,
    RerankerProcessor,
    RestorePIIProcessor,
    SanitizePIIProcessor,
    SemanticRouterProcessor,
    TokenBudgetProcessor,
    VectorSearchProcessor,
)
from src.backend.dsl.engine.processors.ai_banking import (
    AntiFraudScoreProcessor,
    AppealProcessorAI,
    CreditScoringRagProcessor,
    CustomerChatbotProcessor,
    FinDocOcrLlmProcessor,
    KycAmlVerifyProcessor,
    TransactionCategorizerProcessor,
)
from src.backend.dsl.engine.processors.ai_rpa import AIRpaProcessor
from src.backend.dsl.engine.processors.audit import AuditProcessor
from src.backend.dsl.engine.processors.base import (
    BaseProcessor,
    CallableProcessor,
    ProcessorCallable,
)
from src.backend.dsl.engine.processors.batch import (
    BatchDeleteProcessor,
    BatchInsertProcessor,
    BatchUpdateProcessor,
)
from src.backend.dsl.engine.processors.business import (
    ComplianceLabelProcessor,
    CostTrackerProcessor,
    DataMaskingProcessor,
    HumanApprovalProcessor,
    OutboxProcessor,
    TenantScopeProcessor,
)
from src.backend.dsl.engine.processors.cancel_workflow import CancelWorkflowProcessor
from src.backend.dsl.engine.processors.cdc_capture import CDCCaptureProcessor
from src.backend.dsl.engine.processors.components import (
    DatabaseQueryProcessor,
    FileReadProcessor,
    FileWriteProcessor,
    HttpCallProcessor,
    PollingConsumerProcessor,
    S3ReadProcessor,
    S3WriteProcessor,
    TimerProcessor,
)
from src.backend.dsl.engine.processors.composed_message import ComposedMessageProcessor
from src.backend.dsl.engine.processors.control_flow import (
    ChoiceBranch,
    ChoiceProcessor,
    ParallelProcessor,
    PipelineRefProcessor,
    RetryProcessor,
    SagaProcessor,
    SagaStep,
    TryCatchProcessor,
)
from src.backend.dsl.engine.processors.converters import ConvertProcessor
from src.backend.dsl.engine.processors.core import (
    DispatchActionProcessor,
    EnrichProcessor,
    FilterProcessor,
    LogProcessor,
    SetHeaderProcessor,
    SetPropertyProcessor,
    TransformProcessor,
    ValidateProcessor,
)
from src.backend.dsl.engine.processors.data_store import (
    DataStoreDeleteProcessor,
    DataStoreGetProcessor,
    DataStoreSetProcessor,
)
from src.backend.dsl.engine.processors.db_query_external import ExternalDbQueryProcessor
from src.backend.dsl.engine.processors.documents import (
    RenderDocxParams,
    RenderDocxProcessor,
    RenderXlsxParams,
    RenderXlsxProcessor,
)
from src.backend.dsl.engine.processors.eip import (
    AggregatorProcessor,
    CircuitBreakerProcessor,
    ClaimCheckProcessor,
    DeadLetterProcessor,
    DelayProcessor,
    DynamicRouterProcessor,
    FallbackChainProcessor,
    ForEachProcessor,
    IdempotentConsumerProcessor,
    LoadBalancerProcessor,
    LoopProcessor,
    MessageTranslatorProcessor,
    MulticastProcessor,
    NormalizerProcessor,
    OnCompletionProcessor,
    RecipientListProcessor,
    ResequencerProcessor,
    ScatterGatherProcessor,
    SortProcessor,
    SplitterProcessor,
    ThrottlerProcessor,
    TimeoutProcessor,
    WireTapProcessor,
)
from src.backend.dsl.engine.processors.email_trigger import EmailTriggerProcessor
from src.backend.dsl.engine.processors.entity import (
    EntityCreateProcessor,
    EntityDeleteProcessor,
    EntityGetProcessor,
    EntityListProcessor,
    EntityUpdateProcessor,
)
from src.backend.dsl.engine.processors.export import ExportProcessor
from src.backend.dsl.engine.processors.external import (
    AgentGraphProcessor,
    CDCProcessor,
    MCPToolProcessor,
)
from src.backend.dsl.engine.processors.generic import (
    AbTestRouterProcessor,
    BulkheadProcessor,
    FeatureFlagGuardProcessor,
    LineageTrackerProcessor,
    SchemaValidateProcessor,
    ShadowModeProcessor,
    SseSourceProcessor,
)
from src.backend.dsl.engine.processors.graphql_query import GraphQLQueryProcessor
from src.backend.dsl.engine.processors.hitl_approval import HitlApprovalProcessor
from src.backend.dsl.engine.processors.ingest_file import IngestFileProcessor
from src.backend.dsl.engine.processors.integration import (
    EventPublishProcessor,
    MemoryLoadProcessor,
    MemorySaveProcessor,
)
from src.backend.dsl.engine.processors.invoke import InvokeProcessor
from src.backend.dsl.engine.processors.invoke_workflow import InvokeWorkflowProcessor
from src.backend.dsl.engine.processors.ml_predict import MLPredictProcessor
from src.backend.dsl.engine.processors.notify import NotifyProcessor
from src.backend.dsl.engine.processors.patterns import (
    BatchWindowProcessor,
    DebounceProcessor,
    DeduplicateProcessor,
    FormatterProcessor,
    MergeProcessor,
    SwitchProcessor,
)
from src.backend.dsl.engine.processors.rpa import (
    ArchiveProcessor,
    DecryptProcessor,
    EmailComposeProcessor,
    EncryptProcessor,
    ExcelReadProcessor,
    FileMoveProcessor,
    HashProcessor,
    ImageOcrProcessor,
    ImageResizeProcessor,
    PdfMergeProcessor,
    PdfReadProcessor,
    RegexProcessor,
    ShellExecProcessor,
    TemplateRenderProcessor,
    WordReadProcessor,
    WordWriteProcessor,
)
from src.backend.dsl.engine.processors.rpa_banking import (
    AppiumMobileProcessor,
    CitrixSessionProcessor,
    EmailDrivenProcessor,
    KeystrokeReplayProcessor,
    TerminalEmulator3270Processor,
)
from src.backend.dsl.engine.processors.rule_engine import (
    EvaluateRulesParams,
    EvaluateRulesProcessor,
    Rule,
)
from src.backend.dsl.engine.processors.saga_lra import SagaLRAProcessor
from src.backend.dsl.engine.processors.scan_file import ScanFileProcessor
from src.backend.dsl.engine.processors.scraping import (
    ApiProxyProcessor,
    PaginateProcessor,
    ScrapeProcessor,
)
from src.backend.dsl.engine.processors.security import AuthValidateProcessor
from src.backend.dsl.engine.processors.ssh_command import SshCommandProcessor
from src.backend.dsl.engine.processors.streaming import (
    ChannelPurgerProcessor,
    CorrelationIdProcessor,
    DurableSubscriberProcessor,
    ExactlyOnceProcessor,
    GroupByKeyProcessor,
    MessageExpirationProcessor,
    ReplyToProcessor,
    SamplingProcessor,
    SchemaRegistryValidator,
    SessionWindowProcessor,
    SlidingWindowProcessor,
    TumblingWindowProcessor,
)
from src.backend.dsl.engine.processors.template_engine import (
    RenderTemplateFileProcessor,
    RenderTemplateProcessor,
)
from src.backend.dsl.engine.processors.vault_secret import (
    VaultReadResult,
    VaultSecretProcessor,
)
from src.backend.dsl.engine.processors.web import (
    ClickProcessor,
    ExtractProcessor,
    FillFormProcessor,
    NavigateProcessor,
    RunScenarioProcessor,
    ScreenshotProcessor,
)

__all__ = (
    "AIRpaProcessor",
    "AbTestRouterProcessor",
    "AgentGraphProcessor",
    "AggregatorProcessor",
    "AntiFraudScoreProcessor",
    "ApiProxyProcessor",
    "AppealProcessorAI",
    "AppiumMobileProcessor",
    "ArchiveProcessor",
    "AuditProcessor",
    "AuthValidateProcessor",
    "BaseProcessor",
    "BatchDeleteProcessor",
    "BatchInsertProcessor",
    "BatchUpdateProcessor",
    "BatchWindowProcessor",
    "BulkheadProcessor",
    "CDCCaptureProcessor",
    "CDCProcessor",
    "CacheProcessor",
    "CacheWriteProcessor",
    "CallableProcessor",
    "CancelWorkflowProcessor",
    "ChannelPurgerProcessor",
    "ChoiceBranch",
    "ChoiceProcessor",
    "CircuitBreakerProcessor",
    "CitrixSessionProcessor",
    "ClaimCheckProcessor",
    "ClickProcessor",
    "ComplianceLabelProcessor",
    "ComposedMessageProcessor",
    "ConvertProcessor",
    "CorrelationIdProcessor",
    "CostTrackerProcessor",
    "CreditScoringRagProcessor",
    "CustomerChatbotProcessor",
    "DataMaskingProcessor",
    "DataStoreDeleteProcessor",
    "DataStoreGetProcessor",
    "DataStoreSetProcessor",
    "DatabaseQueryProcessor",
    "DeadLetterProcessor",
    "DebounceProcessor",
    "DecryptProcessor",
    "DeduplicateProcessor",
    "DelayProcessor",
    "DispatchActionProcessor",
    "DurableSubscriberProcessor",
    "DynamicRouterProcessor",
    "EmailComposeProcessor",
    "EmailDrivenProcessor",
    "EmailTriggerProcessor",
    "EncryptProcessor",
    "EnrichProcessor",
    "EntityCreateProcessor",
    "EntityDeleteProcessor",
    "EntityGetProcessor",
    "EntityListProcessor",
    "EntityUpdateProcessor",
    "EvaluateRulesParams",
    "EvaluateRulesProcessor",
    "EventPublishProcessor",
    "ExactlyOnceProcessor",
    "ExcelReadProcessor",
    "ExportProcessor",
    "ExternalDbQueryProcessor",
    "ExtractProcessor",
    "FallbackChainProcessor",
    "FeatureFlagGuardProcessor",
    "FileMoveProcessor",
    "FileReadProcessor",
    "FileWriteProcessor",
    "FillFormProcessor",
    "FilterProcessor",
    "FinDocOcrLlmProcessor",
    "ForEachProcessor",
    "FormatterProcessor",
    "GetFeedbackExamplesProcessor",
    "GraphQLQueryProcessor",
    "GroupByKeyProcessor",
    "GuardrailsProcessor",
    "HashProcessor",
    "HitlApprovalProcessor",
    "HttpCallProcessor",
    "HumanApprovalProcessor",
    "IdempotentConsumerProcessor",
    "ImageOcrProcessor",
    "ImageResizeProcessor",
    "IngestFileProcessor",
    "InvokeProcessor",
    "InvokeWorkflowProcessor",
    "KeystrokeReplayProcessor",
    "KycAmlVerifyProcessor",
    "LLMCallProcessor",
    "LLMFallbackProcessor",
    "LLMParserProcessor",
    "LineageTrackerProcessor",
    "LoadBalancerProcessor",
    "LogProcessor",
    "LoopProcessor",
    "MCPToolProcessor",
    "MLPredictProcessor",
    "MemoryLoadProcessor",
    "MemorySaveProcessor",
    "MergeProcessor",
    "MessageExpirationProcessor",
    "MessageTranslatorProcessor",
    "MulticastProcessor",
    "NavigateProcessor",
    "NormalizerProcessor",
    "NotifyProcessor",
    "OnCompletionProcessor",
    "OutboxProcessor",
    "PaginateProcessor",
    "ParallelProcessor",
    "PdfMergeProcessor",
    "PdfReadProcessor",
    "PipelineRefProcessor",
    "PollingConsumerProcessor",
    "ProcessorCallable",
    "PromptComposerProcessor",
    "RagIngestProcessor",
    "RagQueryProcessor",
    "RecipientListProcessor",
    "RegexProcessor",
    "RenderDocxParams",
    "RenderDocxProcessor",
    "RenderTemplateFileProcessor",
    "RenderTemplateProcessor",
    "RenderXlsxParams",
    "RenderXlsxProcessor",
    "ReplyToProcessor",
    "RerankerProcessor",
    "ResequencerProcessor",
    "RestorePIIProcessor",
    "RetryProcessor",
    "Rule",
    "RunScenarioProcessor",
    "S3ReadProcessor",
    "S3WriteProcessor",
    "SagaLRAProcessor",
    "SagaProcessor",
    "SagaStep",
    "SamplingProcessor",
    "SanitizePIIProcessor",
    "ScanFileProcessor",
    "ScatterGatherProcessor",
    "SchemaRegistryValidator",
    "SchemaValidateProcessor",
    "ScrapeProcessor",
    "ScreenshotProcessor",
    "SemanticRouterProcessor",
    "SessionWindowProcessor",
    "SetHeaderProcessor",
    "SetPropertyProcessor",
    "ShadowModeProcessor",
    "ShellExecProcessor",
    "SlidingWindowProcessor",
    "SortProcessor",
    "SplitterProcessor",
    "SseSourceProcessor",
    "SshCommandProcessor",
    "SwitchProcessor",
    "TemplateRenderProcessor",
    "TenantScopeProcessor",
    "TerminalEmulator3270Processor",
    "ThrottlerProcessor",
    "TimeoutProcessor",
    "TimerProcessor",
    "TokenBudgetProcessor",
    "TransactionCategorizerProcessor",
    "TransformProcessor",
    "TryCatchProcessor",
    "TumblingWindowProcessor",
    "ValidateProcessor",
    "VaultReadResult",
    "VaultSecretProcessor",
    "VectorSearchProcessor",
    "WireTapProcessor",
    "WordReadProcessor",
    "WordWriteProcessor",
)
