from pathlib import Path
from typing import ClassVar, Literal

from pydantic import Field
from pydantic_settings import SettingsConfigDict

from app.config.config_loader import BaseSettingsWithLoader
from app.config.constants import ROOT_DIR


__all__ = (
    "AppBaseSettings",
    "app_base_settings",
)


class AppBaseSettings(BaseSettingsWithLoader):
    """Application core configuration settings loaded from YAML files.

    Inherits from BaseYAMLSettings to provide YAML configuration capabilities.
    Validates and manages essential application parameters across environments.
    """

    yaml_group: ClassVar[str] = "app"
    model_config = SettingsConfigDict(
        env_prefix="APP_",
        extra="forbid",
    )

    root_dir: Path = Field(
        default=ROOT_DIR,
        description="Absolute path to project root directory",
        examples=["/usr/src/app", "C:/Projects/my_app"],
    )
    base_url: str = Field(
        ...,
        min_length=1,
        description="Base URL for application endpoints",
        examples=["https://api.example.com", "http://localhost:8000"],
    )
    environment: Literal["development", "staging", "production"] = Field(
        ...,
        description="Current runtime environment (dev/staging/prod)",
        examples=["development", "staging", "production"],
    )
    version: str = Field(
        ...,
        pattern=r"^\d+\.\d+\.\d+$",
        description="Semantic version of the application (major.minor.patch)",
        examples=["1.0.0", "2.3.4", "0.5.1"],
    )
    debug_mode: bool = Field(
        ...,
        description="Flag indicating debug mode status",
        examples=[True, False],
    )
    enable_swagger: bool = Field(
        ...,
        description="Flag indicating swagger status",
        examples=[True, False],
    )
    socket_name: str = Field(
        ...,
        description="Name of the UNIX socket file for FastAPI server",
        examples=["/tmp/fastapi_socket"],
    )


# Pre-initialized settings instance for immediate consumption
app_base_settings = AppBaseSettings()


class SchedulerSettings(BaseSettingsWithLoader):
    """Scheduler configuration settings loaded from YAML files.

    Inherits from BaseYAMLSettings to provide YAML configuration capabilities.
    Validates and manages essential application parameters across environments.
    """

    yaml_group: ClassVar[str] = "scheduler"
    model_config = SettingsConfigDict(
        env_prefix="SCHEDULER_",
        extra="forbid",
    )

    stream_client_event_generated_name: str = Field(
        ...,
        description="Name of the Redis stream event generated by the scheduler",
        examples=["job_generated_event"],
    )
    default_jobstore_name: Literal["default", "backup"] = Field(
        ...,
        description="Default jobstore for the scheduler",
        examples="default",
    )
    backup_jobstore_name: Literal["default", "backup"] = Field(
        ...,
        description="Backup jobstore for the scheduler",
        examples="backup",
    )
    executors: dict = Field(
        ...,
        description="Executors for the scheduler",
        examples={
            "async": {"type": "asyncio"},
            "default": {"type": "threadpool", "max_workers": 20},
        },
    )
    misfire_grace_time: int = Field(
        ...,
        description="Misfire grace time in seconds for the scheduler",
        examples=[60],
    )
    max_instances: int = Field(
        ...,
        description="Maximum number of instances for the scheduler",
        examples=[1],
    )
    timezone: str = Field(
        ...,
        description="Timezone for the scheduler",
        examples=["Europe/Moscow"],
    )
    coalesce: bool = Field(
        ...,
        description="Flag indicating coalescing status for the scheduler",
        examples=[True, False],
    )


# Pre-initialized settings instance for immediate consumption
scheduler_settings = SchedulerSettings()
