"""Plugin entry point for extensions.test_plug."""

from __future__ import annotations

from dataclasses import dataclass

from gd_integration_tools.core.plugin_runtime import BasePlugin


@dataclass
class TestPlugPlugin(BasePlugin):
    """Plugin ``test_plug`` — generated by wizard-plugin S33 W2."""

    name: str = "test_plug"
    version: str = "0.1.0"

    def healthcheck(self) -> bool:
        return True
