# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 5.29.0
# flake8: noqa
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    runtime_version as _runtime_version,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder


_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "orders.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0corders.proto\x12\x06orders"&\n\x12\x43reateOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05"3\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0e\n\x06skb_id\x18\x02 \x01(\t"P\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0e\n\x06skb_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\x96\x01\n\x0cOrderService\x12\x42\n\x0b\x43reateOrder\x12\x1a.orders.CreateOrderRequest\x1a\x15.orders.OrderResponse"\x00\x12\x42\n\x0eGetOrderResult\x12\x17.orders.GetOrderRequest\x1a\x15.orders.OrderResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "orders_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CREATEORDERREQUEST"]._serialized_start = 24
    _globals["_CREATEORDERREQUEST"]._serialized_end = 62
    _globals["_GETORDERREQUEST"]._serialized_start = 64
    _globals["_GETORDERREQUEST"]._serialized_end = 115
    _globals["_ORDERRESPONSE"]._serialized_start = 117
    _globals["_ORDERRESPONSE"]._serialized_end = 197
    _globals["_ORDERSERVICE"]._serialized_start = 200
    _globals["_ORDERSERVICE"]._serialized_end = 350
# @@protoc_insertion_point(module_scope)
