# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auto/orderkinds.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auto/orderkinds.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61uto/orderkinds.proto\x12\x0forderkinds.auto\x1a\x19google/protobuf/any.proto\"}\n\x11OrderKindSchemaIn\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08skb_uuid\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x07\n\x05_nameB\x0e\n\x0c_descriptionB\x0b\n\t_skb_uuid\"\xde\x01\n\x12OrderKindSchemaOut\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08skb_uuid\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\n\n\x02id\x18\x04 \x01(\x03\x12(\n\ncreated_at\x18\x05 \x01(\x0b\x32\x14.google.protobuf.Any\x12(\n\nupdated_at\x18\x06 \x01(\x0b\x32\x14.google.protobuf.AnyB\x07\n\x05_nameB\x0e\n\x0c_descriptionB\x0b\n\t_skb_uuid\"\x0f\n\rEmptyResponse\"\x0e\n\x0c\x45mptyRequest2\xa6\x03\n\x15OrderkindsAutoService\x12Q\n\x06\x43reate\x12\".orderkinds.auto.OrderKindSchemaIn\x1a#.orderkinds.auto.OrderKindSchemaOut\x12P\n\nCreateMany\x12\".orderkinds.auto.OrderKindSchemaIn\x1a\x1e.orderkinds.auto.EmptyResponse\x12I\n\x03Get\x12\x1d.orderkinds.auto.EmptyRequest\x1a#.orderkinds.auto.OrderKindSchemaOut\x12J\n\x04List\x12\x1d.orderkinds.auto.EmptyRequest\x1a#.orderkinds.auto.OrderKindSchemaOut\x12Q\n\x06Update\x12\".orderkinds.auto.OrderKindSchemaIn\x1a#.orderkinds.auto.OrderKindSchemaOutb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auto.orderkinds_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERKINDSCHEMAIN']._serialized_start=69
  _globals['_ORDERKINDSCHEMAIN']._serialized_end=194
  _globals['_ORDERKINDSCHEMAOUT']._serialized_start=197
  _globals['_ORDERKINDSCHEMAOUT']._serialized_end=419
  _globals['_EMPTYRESPONSE']._serialized_start=421
  _globals['_EMPTYRESPONSE']._serialized_end=436
  _globals['_EMPTYREQUEST']._serialized_start=438
  _globals['_EMPTYREQUEST']._serialized_end=452
  _globals['_ORDERKINDSAUTOSERVICE']._serialized_start=455
  _globals['_ORDERKINDSAUTOSERVICE']._serialized_end=877
# @@protoc_insertion_point(module_scope)
