# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auto/users.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auto/users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61uto/users.proto\x12\nusers.auto\x1a\x19google/protobuf/any.proto\"H\n\x0cUserSchemaIn\x12\x10\n\x08username\x18\x01 \x01(\t\x12&\n\x08password\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"\xf2\x01\n\rUserSchemaOut\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12(\n\x05\x65mail\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x88\x01\x01\x12(\n\ncreated_at\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12-\n\nupdated_at\x18\x05 \x01(\x0b\x32\x14.google.protobuf.AnyH\x01\x88\x01\x01\x12\x14\n\x0cis_superuser\x18\x06 \x01(\x08\x12\x11\n\tis_active\x18\x07 \x01(\x08\x42\x08\n\x06_emailB\r\n\x0b_updated_at\"\x0f\n\rEmptyResponse\"\x0e\n\x0c\x45mptyRequest2\xcc\x02\n\x10UsersAutoService\x12=\n\x06\x43reate\x12\x18.users.auto.UserSchemaIn\x1a\x19.users.auto.UserSchemaOut\x12\x41\n\nCreateMany\x12\x18.users.auto.UserSchemaIn\x1a\x19.users.auto.EmptyResponse\x12:\n\x03Get\x12\x18.users.auto.EmptyRequest\x1a\x19.users.auto.UserSchemaOut\x12;\n\x04List\x12\x18.users.auto.EmptyRequest\x1a\x19.users.auto.UserSchemaOut\x12=\n\x06Update\x12\x18.users.auto.UserSchemaIn\x1a\x19.users.auto.UserSchemaOutb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auto.users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERSCHEMAIN']._serialized_start=59
  _globals['_USERSCHEMAIN']._serialized_end=131
  _globals['_USERSCHEMAOUT']._serialized_start=134
  _globals['_USERSCHEMAOUT']._serialized_end=376
  _globals['_EMPTYRESPONSE']._serialized_start=378
  _globals['_EMPTYRESPONSE']._serialized_end=393
  _globals['_EMPTYREQUEST']._serialized_start=395
  _globals['_EMPTYREQUEST']._serialized_end=409
  _globals['_USERSAUTOSERVICE']._serialized_start=412
  _globals['_USERSAUTOSERVICE']._serialized_end=744
# @@protoc_insertion_point(module_scope)
