"""empty message

Revision ID: 2a6552f7e7f0
Revises: 8fcd08f33d18
Create Date: 2024-12-05 17:37:01.908378

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2a6552f7e7f0"
down_revision: Union[str, None] = "8fcd08f33d18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
