"""empty message

Revision ID: ac8f2bc96714
Revises: 15be6e184581
Create Date: 2024-12-19 10:50:32.399916

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ac8f2bc96714"
down_revision: Union[str, None] = "15be6e184581"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "is_send_request_to_skb", sa.Boolean(), server_default="f", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "is_send_request_to_skb")
    # ### end Alembic commands ###
