"""Docs Generator — pure-Python Markdown export (Wave 2 DX #60)."""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from src.backend.core.registry_explorer.explorer import RegistryExplorer

logger = logging.getLogger(__name__)

__all__ = ("DocsGenerator", "get_docs_generator")


class DocsGenerator:
    """Auto-generate Markdown docs из RegistryExplorer."""

    def generate_routes_md(self, explorer: "RegistryExplorer") -> str:
        """Generate routes/index.md content."""
        routes = explorer.list_routes()
        lines: list[str] = []
        lines.append("# Routes")
        lines.append("")
        lines.append(
            f"_Auto-generated by DocsGenerator at {datetime.now(UTC).isoformat()}_"
        )
        lines.append("")
        lines.append(f"Total routes: **{len(routes)}**")
        lines.append("")
        # Group by owner.
        by_owner: dict[str, list[Any]] = {}
        for r in routes:
            by_owner.setdefault(r.owner or "(no owner)", []).append(r)

        for owner in sorted(by_owner.keys()):
            lines.append(f"## Owner: {owner}")
            lines.append("")
            lines.append("| ID | Source | Timeout (s) | Tags | Tenant |")
            lines.append("|----|-------|-------------|------|--------|")
            for r in sorted(by_owner[owner], key=lambda x: x.id):
                tags = ", ".join(r.tags) if r.tags else "—"
                lines.append(
                    f"| `{r.id}` | `{r.source}` | "
                    f"{r.timeout_seconds} | {tags} | {r.tenant_id} |"
                )
            lines.append("")

        # Search reference.
        lines.append("## Search by filters")
        lines.append("")
        lines.append("```python")
        lines.append(
            "from src.backend.core.registry_explorer import get_registry_explorer"
        )
        lines.append("e = get_registry_explorer()")
        lines.append("# Search by owner/tag/tenant.")
        lines.append("critical_routes = e.search_routes(tag='critical')")
        lines.append("```")
        lines.append("")
        return "\n".join(lines)

    def generate_connectors_md(self, explorer: "RegistryExplorer") -> str:
        """Generate connectors/index.md content."""
        connectors = explorer.list_connectors()
        lines: list[str] = []
        lines.append("# Connectors")
        lines.append("")
        lines.append(
            f"_Auto-generated by DocsGenerator at {datetime.now(UTC).isoformat()}_"
        )
        lines.append("")
        lines.append(f"Total connectors: **{len(connectors)}**")
        lines.append("")
        # Group by category.
        by_category: dict[str, list[Any]] = {}
        for c in connectors:
            by_category.setdefault(c.category or "(no category)", []).append(c)

        for category in sorted(by_category.keys()):
            lines.append(f"## Category: {category}")
            lines.append("")
            lines.append("| Name | Auth | Base URL | Version | Owner | Tags |")
            lines.append("|------|------|----------|---------|-------|------|")
            for c in sorted(by_category[category], key=lambda x: x.name):
                tags = ", ".join(c.tags) if c.tags else "—"
                lines.append(
                    f"| `{c.name}` | {c.auth} | "
                    f"`{c.base_url or '—'}` | {c.version or '—'} | "
                    f"{c.owner or '—'} | {tags} |"
                )
            lines.append("")

        return "\n".join(lines)

    def generate_actions_md(self, explorer: "RegistryExplorer") -> str:
        """Generate actions/index.md content."""
        actions = explorer.list_actions()
        lines: list[str] = []
        lines.append("# Actions")
        lines.append("")
        lines.append(
            f"_Auto-generated by DocsGenerator at {datetime.now(UTC).isoformat()}_"
        )
        lines.append("")
        lines.append(f"Total actions: **{len(actions)}**")
        lines.append("")
        lines.append("| Name | Side Effect | Owner | Params | Tags |")
        lines.append("|------|-------------|-------|--------|------|")
        for a in sorted(actions, key=lambda x: x.name):
            params = ", ".join(a.params) if a.params else "—"
            tags = ", ".join(a.tags) if a.tags else "—"
            lines.append(
                f"| `{a.name}` | {a.side_effect or '—'} | "
                f"{a.owner or '—'} | {params} | {tags} |"
            )
        lines.append("")
        return "\n".join(lines)

    def generate_index(self, sections: dict[str, str]) -> str:
        """Generate top-level index.md."""
        lines: list[str] = []
        lines.append("# Generated Docs")
        lines.append("")
        lines.append(
            f"_Auto-generated by DocsGenerator at {datetime.now(UTC).isoformat()}_"
        )
        lines.append("")
        lines.append("## Sections")
        lines.append("")
        for section_name, content in sections.items():
            # Extract first heading from content.
            first_heading = section_name
            for line in content.split("\n"):
                if line.startswith("# "):
                    first_heading = line[2:].strip()
                    break
            lines.append(f"- [{first_heading}]({section_name}/index.md)")
        lines.append("")
        return "\n".join(lines)

    def export_docs(
        self, sections: dict[str, str], target_dir: str | Path
    ) -> list[Path]:
        """Write all sections в target_dir.

        Args:
            sections: {"section_name": content_str}.
            target_dir: Base directory.

        Returns:
            List of written file paths.
        """
        target = Path(target_dir)
        target.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []

        # Write each section.
        for section_name, content in sections.items():
            section_dir = target / section_name
            section_dir.mkdir(parents=True, exist_ok=True)
            section_file = section_dir / "index.md"
            section_file.write_text(content, encoding="utf-8")
            written.append(section_file)
            logger.info("Wrote %s (%d bytes)", section_file, len(content))

        # Write top-level index.
        if len(sections) > 1:
            index = self.generate_index(sections)
            index_file = target / "index.md"
            index_file.write_text(index, encoding="utf-8")
            written.append(index_file)
            logger.info("Wrote %s (%d bytes)", index_file, len(index))

        return written


_generator: DocsGenerator | None = None


def get_docs_generator() -> DocsGenerator:
    """Singleton-доступ к общему ``DocsGenerator``."""
    global _generator
    if _generator is None:
        _generator = DocsGenerator()
    return _generator


def reset_docs_generator() -> None:
    """Сбросить singleton (следующий ``get_`` создаст новый)."""
    global _generator
    _generator = None


def cli_main() -> int:
    """CLI entry point для `python -m src.backend.core.docs_generator generate`.

    Usage:
        python -m src.backend.core.docs_generator generate \\
            --registry-explorers --sla-cockpit --cdc-control-plane \\
            --output docs/generated/
    """
    import argparse
    from pathlib import Path as _Path

    parser = argparse.ArgumentParser(
        description="Generate Markdown docs from registry explorers"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    gen_p = sub.add_parser("generate", help="Generate docs from explorers")
    gen_p.add_argument(
        "--registry-explorers",
        action="store_true",
        help="Include routes/connectors/actions from RegistryExplorer",
    )
    gen_p.add_argument(
        "--sla-cockpit",
        action="store_true",
        help="Include SLA/SLO snapshot from sla_cockpit",
    )
    gen_p.add_argument(
        "--cdc-control-plane",
        action="store_true",
        help="Include CDC slots snapshot from cdc_control_plane",
    )
    gen_p.add_argument(
        "--output",
        type=_Path,
        default=_Path("docs/generated"),
        help="Output directory (default: docs/generated/)",
    )

    args = parser.parse_args()
    if args.command != "generate":
        parser.print_help()
        return 1

    sections: dict[str, str] = {}
    gen = DocsGenerator()

    if args.registry_explorers:
        from src.backend.core.registry_explorer import RouteEntry, get_registry_explorer

        explorer = get_registry_explorer()
        # Best-effort auto-seed from existing connectors.
        try:
            explorer.clear()
            from src.backend.core.connectors import get_connector_registry

            for connector in get_connector_registry().list_all():
                meta = connector.metadata()
                explorer.register_connector(
                    type(meta)(
                        name=getattr(meta, "name", connector.__class__.__name__),
                        category=getattr(meta, "category", "unknown"),
                        auth=getattr(meta, "auth_model", "unknown"),
                    )
                )
        except Exception:
            pass

        # Best-effort seed routes.
        try:
            explorer.register_route(
                RouteEntry(
                    id="order-create",
                    source="timer:60s",
                    owner="team-payments",
                    tags=("prod",),
                )
            )
            explorer.register_route(
                RouteEntry(
                    id="dadata-enrich",
                    source="action:order-create",
                    owner="team-payments",
                    tags=("prod",),
                )
            )
        except Exception:
            pass

        sections["routes"] = gen.generate_routes_md(explorer)
        sections["connectors"] = gen.generate_connectors_md(explorer)
        sections["actions"] = gen.generate_actions_md(explorer)

    if args.sla_cockpit:
        try:
            from src.backend.core.sla_cockpit import get_sla_cockpit

            cockpit = get_sla_cockpit()
            md = "# SLA Snapshot\n\n"
            report = cockpit.generate_report()
            for e in report.evaluations[:20]:
                md += f"- **{e.tenant_id}/{e.route_id}**: `{e.status.value}`\n"
            sections["sla"] = md
        except Exception:
            sections["sla"] = "# SLA Snapshot\n\n_SLA Cockpit not available._\n"

    if args.cdc_control_plane:
        try:
            from src.backend.core.cdc_control_plane import get_cdc_control_plane

            plane = get_cdc_control_plane()
            md = "# CDC Control Plane\n\n"
            for status in plane.list_statuses()[:20]:
                md += (
                    f"- **{status['name']}** "
                    f"({status.get('table', 'n/a')}): "
                    f"status=`{status['status']}` "
                    f"offset={status['offset']['value']}\n"
                )
            sections["cdc"] = md
        except Exception:
            sections["cdc"] = "# CDC Control Plane\n\n_Plane not available._\n"

    if not sections:
        parser.error(
            "No sections selected. Use --registry-explorers / "
            "--sla-cockpit / --cdc-control-plane."
        )

    written = gen.export_docs(sections, args.output)
    print(f"Wrote {len(written)} files to {args.output}")
    for path in written:
        print(f"  {path}")
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(cli_main())
