"""empty message

Revision ID: f2ebd76de040
Revises: 8d6694909449
Create Date: 2024-11-25 18:03:30.378479

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2ebd76de040"
down_revision: Union[str, None] = "8d6694909449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "files", "Данные файлов", existing_comment=None, schema=None
    )
    op.create_table_comment(
        "orderkinds", "Виды запросов в СКБ-Техно", existing_comment=None, schema=None
    )
    op.create_table_comment(
        "orders", "Запросы в СКБ-Техно", existing_comment=None, schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("orders", existing_comment="Запросы в СКБ-Техно", schema=None)
    op.drop_table_comment(
        "orderkinds", existing_comment="Виды запросов в СКБ-Техно", schema=None
    )
    op.drop_table_comment("files", existing_comment="Данные файлов", schema=None)
    # ### end Alembic commands ###
