"""empty message

Revision ID: ea79a4853c74
Revises: 09e76b08f3f6
Create Date: 2024-11-20 15:15:15.764675

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea79a4853c74"
down_revision: Union[str, None] = "09e76b08f3f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_files_object_uuid"), "files", ["object_uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_object_uuid"), table_name="files")
    # ### end Alembic commands ###
