"""empty message

Revision ID: c8cbd4f31af5
Revises: b213785cb5a9
Create Date: 2024-12-05 17:35:06.533982

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c8cbd4f31af5"
down_revision: Union[str, None] = "b213785cb5a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=False))
    op.drop_constraint("uq_users_email", "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_username"), "users", ["username"])
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    op.drop_column("users", "username")
    # ### end Alembic commands ###
