"""Initial commit

Revision ID: d631df619fb5
Revises: b73a5b3a4262
Create Date: 2024-11-07 18:46:47.861361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd631df619fb5'
down_revision: Union[str, None] = 'b73a5b3a4262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_send_to_gd')
    op.drop_column('orders', 'is_active')
    op.drop_column('orders', 'errors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('errors', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('is_send_to_gd', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
