"""empty message

Revision ID: ec8beb1f945d
Revises: 35ab509b35cb
Create Date: 2024-11-20 15:51:06.766823

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ec8beb1f945d"
down_revision: Union[str, None] = "35ab509b35cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("linked_object_id", sa.Integer(), nullable=True))
    op.drop_constraint("fk_orders_file_id_files", "orders", type_="foreignkey")
    op.drop_column("orders", "file_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("file_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "fk_orders_file_id_files", "orders", "files", ["file_id"], ["id"]
    )
    op.drop_column("files", "linked_object_id")
    # ### end Alembic commands ###
