"""Initial commit

Revision ID: 5f53dbea2ec3
Revises: 
Create Date: 2024-11-07 18:44:37.590199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f53dbea2ec3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderkinds',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skb_uuid', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orderkinds'))
    )
    op.create_index(op.f('ix_orderkinds_skb_uuid'), 'orderkinds', ['skb_uuid'], unique=True)
    op.create_table('orders',
    sa.Column('order_kind_id', sa.Integer(), nullable=False),
    sa.Column('pledge_gd_id', sa.Integer(), nullable=False),
    sa.Column('pledge_cadastral_number', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_send_to_gd', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('errors', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_kind_id'], ['orderkinds.id'], name=op.f('fk_orders_order_kind_id_orderkinds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_index(op.f('ix_orderkinds_skb_uuid'), table_name='orderkinds')
    op.drop_table('orderkinds')
    # ### end Alembic commands ###
