"""empty message

Revision ID: 5bdea6203c7a
Revises: ea79a4853c74
Create Date: 2024-11-20 15:36:13.551402

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5bdea6203c7a"
down_revision: Union[str, None] = "ea79a4853c74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
