"""empty message

Revision ID: 6463ce389e56
Revises: ea95460c4aad
Create Date: 2024-11-22 12:45:36.972285

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6463ce389e56"
down_revision: Union[str, None] = "ea95460c4aad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orderfiless",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_orderfiless_file_id_files")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_orderfiless_order_id_orders")
        ),
        sa.PrimaryKeyConstraint(
            "order_id", "file_id", "id", name=op.f("pk_orderfiless")
        ),
        comment="Связь заказов и файлов",
    )
    op.drop_column("files", "linked_object_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column("linked_object_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_table("orderfiless")
    # ### end Alembic commands ###
