# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auto/files.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auto/files.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61uto/files.proto\x12\nfiles.auto\x1a\x19google/protobuf/any.proto\"N\n\x0c\x46ileSchemaIn\x12.\n\x0bobject_uuid\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x88\x01\x01\x42\x0e\n\x0c_object_uuid\"\xcb\x01\n\rFileSchemaOut\x12.\n\x0bobject_uuid\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x88\x01\x01\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x11\n\x04name\x18\x03 \x01(\tH\x01\x88\x01\x01\x12(\n\ncreated_at\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12(\n\nupdated_at\x18\x05 \x01(\x0b\x32\x14.google.protobuf.AnyB\x0e\n\x0c_object_uuidB\x07\n\x05_name\"\x0f\n\rEmptyResponse\"\x0e\n\x0c\x45mptyRequest2\xcc\x02\n\x10\x46ilesAutoService\x12=\n\x06\x43reate\x12\x18.files.auto.FileSchemaIn\x1a\x19.files.auto.FileSchemaOut\x12\x41\n\nCreateMany\x12\x18.files.auto.FileSchemaIn\x1a\x19.files.auto.EmptyResponse\x12:\n\x03Get\x12\x18.files.auto.EmptyRequest\x1a\x19.files.auto.FileSchemaOut\x12;\n\x04List\x12\x18.files.auto.EmptyRequest\x1a\x19.files.auto.FileSchemaOut\x12=\n\x06Update\x12\x18.files.auto.FileSchemaIn\x1a\x19.files.auto.FileSchemaOutb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auto.files_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILESCHEMAIN']._serialized_start=59
  _globals['_FILESCHEMAIN']._serialized_end=137
  _globals['_FILESCHEMAOUT']._serialized_start=140
  _globals['_FILESCHEMAOUT']._serialized_end=343
  _globals['_EMPTYRESPONSE']._serialized_start=345
  _globals['_EMPTYRESPONSE']._serialized_end=360
  _globals['_EMPTYREQUEST']._serialized_start=362
  _globals['_EMPTYREQUEST']._serialized_end=376
  _globals['_FILESAUTOSERVICE']._serialized_start=379
  _globals['_FILESAUTOSERVICE']._serialized_end=711
# @@protoc_insertion_point(module_scope)
