# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from auto import orders_pb2 as auto_dot_orders__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auto/orders_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrdersAutoServiceStub(object):
    """Авто-сгенерированный сервис для домена 'orders' (Wave 1.3 Roadmap V10).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/orders.auto.OrdersAutoService/Create',
                request_serializer=auto_dot_orders__pb2.OrderSchemaIn.SerializeToString,
                response_deserializer=auto_dot_orders__pb2.OrderSchemaOut.FromString,
                _registered_method=True)
        self.CreateMany = channel.unary_unary(
                '/orders.auto.OrdersAutoService/CreateMany',
                request_serializer=auto_dot_orders__pb2.OrderSchemaIn.SerializeToString,
                response_deserializer=auto_dot_orders__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/orders.auto.OrdersAutoService/Get',
                request_serializer=auto_dot_orders__pb2.EmptyRequest.SerializeToString,
                response_deserializer=auto_dot_orders__pb2.OrderSchemaOut.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/orders.auto.OrdersAutoService/List',
                request_serializer=auto_dot_orders__pb2.EmptyRequest.SerializeToString,
                response_deserializer=auto_dot_orders__pb2.OrderSchemaOut.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/orders.auto.OrdersAutoService/Update',
                request_serializer=auto_dot_orders__pb2.OrderSchemaIn.SerializeToString,
                response_deserializer=auto_dot_orders__pb2.OrderSchemaOut.FromString,
                _registered_method=True)


class OrdersAutoServiceServicer(object):
    """Авто-сгенерированный сервис для домена 'orders' (Wave 1.3 Roadmap V10).
    """

    def Create(self, request, context):
        """Создаёт новый объект ресурса 'orders'.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMany(self, request, context):
        """Создаёт несколько объектов ресурса 'orders'.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Возвращает объект ресурса 'orders' по идентификатору.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Возвращает список объектов ресурса 'orders'.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Обновляет объект ресурса 'orders'.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrdersAutoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=auto_dot_orders__pb2.OrderSchemaIn.FromString,
                    response_serializer=auto_dot_orders__pb2.OrderSchemaOut.SerializeToString,
            ),
            'CreateMany': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMany,
                    request_deserializer=auto_dot_orders__pb2.OrderSchemaIn.FromString,
                    response_serializer=auto_dot_orders__pb2.EmptyResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=auto_dot_orders__pb2.EmptyRequest.FromString,
                    response_serializer=auto_dot_orders__pb2.OrderSchemaOut.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=auto_dot_orders__pb2.EmptyRequest.FromString,
                    response_serializer=auto_dot_orders__pb2.OrderSchemaOut.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=auto_dot_orders__pb2.OrderSchemaIn.FromString,
                    response_serializer=auto_dot_orders__pb2.OrderSchemaOut.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.auto.OrdersAutoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orders.auto.OrdersAutoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrdersAutoService(object):
    """Авто-сгенерированный сервис для домена 'orders' (Wave 1.3 Roadmap V10).
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.auto.OrdersAutoService/Create',
            auto_dot_orders__pb2.OrderSchemaIn.SerializeToString,
            auto_dot_orders__pb2.OrderSchemaOut.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.auto.OrdersAutoService/CreateMany',
            auto_dot_orders__pb2.OrderSchemaIn.SerializeToString,
            auto_dot_orders__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.auto.OrdersAutoService/Get',
            auto_dot_orders__pb2.EmptyRequest.SerializeToString,
            auto_dot_orders__pb2.OrderSchemaOut.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.auto.OrdersAutoService/List',
            auto_dot_orders__pb2.EmptyRequest.SerializeToString,
            auto_dot_orders__pb2.OrderSchemaOut.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.auto.OrdersAutoService/Update',
            auto_dot_orders__pb2.OrderSchemaIn.SerializeToString,
            auto_dot_orders__pb2.OrderSchemaOut.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
