"""Unit-тесты :class:`RequestContextMiddleware` (ADR-NEW-3, Sprint 17).

Покрытие:
    * correlation_id из X-Correlation-ID header → в ContextVar;
    * autogen correlation_id при отсутствии header;
    * tenant_id из X-Tenant-ID header → в ContextVar;
    * RequestContext.current() возвращает snapshot inside ASGI;
    * scope["state"]["correlation_id"] backward-compat установлен;
    * scope["state"]["request_context"] установлен;
    * RequestContext.current() == None после shutdown.
"""

# ruff: noqa: S101

from __future__ import annotations

from typing import Any

import pytest

from src.backend.core.request_context import RequestContext
from src.backend.entrypoints.middlewares.request_context import RequestContextMiddleware


class _CapturingApp:
    """ASGI-приложение-стаб, фиксирует scope/ctx при вызове."""

    def __init__(self) -> None:
        self.captured_scope: dict[str, Any] | None = None
        self.captured_ctx: RequestContext | None = None

    async def __call__(
        self, scope: dict[str, Any], receive: Any, send: Any
    ) -> None:
        self.captured_scope = scope
        self.captured_ctx = RequestContext.current()


def _scope(
    headers: list[tuple[bytes, bytes]] | None = None,
    state: dict[str, Any] | None = None,
    method: str = "GET",
    path: str = "/api/v1/x",
    scope_type: str = "http",
) -> dict[str, Any]:
    """Минимальный ASGI scope."""
    return {
        "type": scope_type,
        "method": method,
        "path": path,
        "headers": headers or [],
        "state": state or {},
    }


async def _noop_receive() -> dict[str, Any]:  # pragma: no cover
    return {"type": "http.disconnect"}


async def _noop_send(_message: dict[str, Any]) -> None:  # pragma: no cover
    return None


class TestRequestContextMiddleware:
    """ADR-NEW-3 core behavior."""

    async def test_correlation_from_header(self) -> None:
        app = _CapturingApp()
        mw = RequestContextMiddleware(app)
        scope = _scope(
            headers=[(b"x-correlation-id", b"abc-corr-42")],
        )
        await mw(scope, _noop_receive, _noop_send)
        assert app.captured_ctx is not None
        assert app.captured_ctx.correlation_id == "abc-corr-42"

    async def test_correlation_autogenerated(self) -> None:
        app = _CapturingApp()
        mw = RequestContextMiddleware(app)
        scope = _scope()
        await mw(scope, _noop_receive, _noop_send)
        assert app.captured_ctx is not None
        assert len(app.captured_ctx.correlation_id) >= 8

    async def test_tenant_id_from_header(self) -> None:
        app = _CapturingApp()
        mw = RequestContextMiddleware(app)
        scope = _scope(
            headers=[(b"x-tenant-id", b"tenant-007")],
        )
        await mw(scope, _noop_receive, _noop_send)
        assert app.captured_ctx is not None
        assert app.captured_ctx.tenant_id == "tenant-007"

    async def test_request_id_from_header(self) -> None:
        app = _CapturingApp()
        mw = RequestContextMiddleware(app)
        scope = _scope(
            headers=[(b"x-request-id", b"req-12345")],
        )
        await mw(scope, _noop_receive, _noop_send)
        assert app.captured_ctx is not None
        assert app.captured_ctx.request_id == "req-12345"

    async def test_method_and_path_recorded(self) -> None:
        app = _CapturingApp()
        mw = RequestContextMiddleware(app)
        scope = _scope(method="POST", path="/api/v1/orders")
        await mw(scope, _noop_receive, _noop_send)
        assert app.captured_ctx is not None
        assert app.captured_ctx.method == "POST"
        assert app.captured_ctx.path == "/api/v1/orders"

    async def test_scope_state_backward_compat(self) -> None:
        app = _CapturingApp()
        mw = RequestContextMiddleware(app)
        scope = _scope(headers=[(b"x-correlation-id", b"corr-bc")])
        await mw(scope, _noop_receive, _noop_send)
        assert scope["state"]["correlation_id"] == "corr-bc"
        assert isinstance(scope["state"]["request_context"], RequestContext)

    async def test_context_cleared_after_call(self) -> None:
        app = _CapturingApp()
        mw = RequestContextMiddleware(app)
        scope = _scope(headers=[(b"x-correlation-id", b"corr-clr")])
        await mw(scope, _noop_receive, _noop_send)
        # Внутри ASGI: установлен
        assert app.captured_ctx is not None
        assert app.captured_ctx.correlation_id == "corr-clr"
        # Снаружи: сброшен
        assert RequestContext.current() is None

    async def test_non_http_scope_passthrough(self) -> None:
        app = _CapturingApp()
        mw = RequestContextMiddleware(app)
        scope = _scope(scope_type="lifespan")
        await mw(scope, _noop_receive, _noop_send)
        # No ContextVar bind for non-http
        assert app.captured_ctx is None


@pytest.mark.parametrize(
    ("header_name", "header_value", "expected"),
    [
        (b"X-Correlation-ID", b"upper-case-header", "upper-case-header"),
        (b"x-correlation-id", b"lower-case-header", "lower-case-header"),
        (b"X-CORRELATION-ID", b"all-caps", "all-caps"),
    ],
)
async def test_header_case_insensitive(
    header_name: bytes, header_value: bytes, expected: str
) -> None:
    """Заголовки case-insensitive."""
    app = _CapturingApp()
    mw = RequestContextMiddleware(app)
    scope = _scope(headers=[(header_name, header_value)])
    await mw(scope, _noop_receive, _noop_send)
    assert app.captured_ctx is not None
    assert app.captured_ctx.correlation_id == expected
