#!/usr/bin/env python3
"""Generate docs/adr/WIKI.md (chronological summary) from ADR files.

Парсит все ADR-файлы в docs/adr/ и создаёт WIKI.md с:
- Сортировка по slot (newest first)
- Extract status из первой строки "* Статус: ... *"
- Sprint tag (если есть)
- Сводка по спринтам

Запуск: `python tools/build_adr_wiki.py`
Аналогично tools/build_adr_index.py, но wiki-style (chronological + summary).

S42 W3 — ADR→wiki sync (Sprint 42 DoD #3).
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ADR_DIR = ROOT / "docs" / "adr"
OUT = ADR_DIR / "WIKI.md"

_NUM_RE = re.compile(r"^(\d{3,4})-(.+)\.md$")
_STATUS_RE = re.compile(r"^\*\s*Статус:\s*(.+?)\s*\*", re.MULTILINE)
_DATE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")
# Match both "Sprint 40 W1" and "S40 W1" formats. "Sprint 40" → group(1)="40".
_SPRINT_RE = re.compile(r"S(?:print)?\s*(\d+)\s*W(\d+)", re.IGNORECASE)


def _parse_adr(path: Path) -> dict[str, str] | None:
    """Parse one ADR file → dict(slug, title, status, date, sprint) or None."""
    m = _NUM_RE.match(path.name)
    if not m:
        return None
    slot, _ = m.groups()
    src = path.read_text(encoding="utf-8")

    # Title: первая строка "# ADR-XXXX — ..."
    title = ""
    for line in src.splitlines():
        if line.startswith("# "):
            title = line.lstrip("# ").strip()
            # Strip leading "ADR-XXXX — " или "ADR-XXXX: "
            title = re.sub(r"^ADR-\d{3,4}[:\s—\-]+", "", title)
            break

    # Status: первая строка "* Статус: ... *"
    status_m = _STATUS_RE.search(src)
    status = status_m.group(1) if status_m else "—"

    # Date: первое YYYY-MM-DD
    date_m = _DATE_RE.search(src)
    date_str = date_m.group(1) if date_m else "—"

    # Sprint: первое "S## W##" в status line (e.g., "S40 W1" или "Sprint 40 W1")
    sprint_m = _SPRINT_RE.search(status)
    sprint = (
        f"S{sprint_m.group(1)} W{sprint_m.group(2)}"
        if sprint_m
        else "—"
    )

    return {
        "slot": slot,
        "title": title,
        "status": status,
        "date": date_str,
        "sprint": sprint,
    }


def _main() -> int:
    if not ADR_DIR.is_dir():
        print(f"[ERROR] ADR dir not found: {ADR_DIR}", file=sys.stderr)
        return 1

    adrs: list[dict[str, str]] = []
    for path in sorted(ADR_DIR.glob("*.md"), reverse=True):
        parsed = _parse_adr(path)
        if parsed:
            adrs.append(parsed)

    if not adrs:
        print("[WARN] no ADR files found", file=sys.stderr)
        return 0

    # Sprint snapshot
    sprint_counts: dict[str, int] = {}
    for a in adrs:
        s = a["sprint"]
        if s == "—":
            continue
        # Group by base sprint (e.g., "S41 W1" → "S41")
        base = re.match(r"(S\d+)", s, re.IGNORECASE)
        if base:
            key = base.group(1).upper()
            sprint_counts[key] = sprint_counts.get(key, 0) + 1

    # Generate WIKI.md
    today = date.today().isoformat()
    lines: list[str] = [
        "# ADR Wiki — Chronological Summary",
        "",
        f"> Auto-generated by `tools/build_adr_wiki.py` ({today}).",
        "> Не редактировать вручную — изменения будут перезаписаны при следующем sync.",
        "",
        "Quick navigation: [INDEX.md](INDEX.md) (slot-based) · [directory](.)",
        "",
        "## Active ADRs (chronological, newest first)",
        "",
        "<!-- adr_wiki:start — auto-populated by tools/build_adr_wiki.py -->",
        "",
        "| # | Title | Status | Date | Sprint |",
        "|---|-------|--------|------|--------|",
    ]

    for a in adrs[:50]:  # top 50 newest (rest в полном INDEX.md)
        title_esc = a["title"].replace("|", "\\|")
        status_esc = a["status"].replace("|", "\\|")
        lines.append(
            f"| {a['slot']} | {title_esc} | {status_esc} | {a['date']} | {a['sprint']} |"
        )

    lines.extend(
        [
            "",
            f"*Всего: {len(adrs)} ADR-файлов. Показано топ-50 (newest first).*",
            "",
            "<!-- adr_wiki:end -->",
            "",
            "## Как используется",
            "",
            "- **Index by slot**: [INDEX.md](INDEX.md) (table view, linked to filenames).",
            "- **This file (WIKI.md)**: chronological summary, status, sprint tags.",
            "- **Sphinx integration**: каждый ADR rendered в `docs/_build/html/adr/`",
            "  (via docs.yml + autoapi extension). GitHub Pages deployment via",
            "  `docs-publish.yml` (`gh-pages` branch).",
            "- **Sync mechanism**: `.github/workflows/adr-sync.yml` triggers on",
            "  `docs/adr/**` push, regenerates this file via",
            "  `tools/build_adr_wiki.py`, commits back to main.",
            "",
            "## Sprint snapshot",
            "",
            "| Sprint | ADRs added |",
            "|--------|-----------|",
        ]
    )

    for sprint in sorted(sprint_counts.keys(), reverse=True)[:10]:
        lines.append(f"| {sprint} | {sprint_counts[sprint]} |")

    lines.extend(
        [
            "",
            "См. также: [PLAN.md](../../PLAN.md), [CHANGELOG.md](../../CHANGELOG.md),",
            "[TECH_DEBT.md](../../../.shared/context/TECH_DEBT.md).",
            "",
        ]
    )

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"OK adr_wiki: {len(adrs)} files → {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(_main())
