#!/usr/bin/env python3
"""make wizard-plugin — Typer-based interactive CLI для создания plugin scaffold (S33 W2).

Генерирует:
- ``extensions/<name>/plugin.toml``
- ``extensions/<name>/__init__.py``
- ``extensions/<name>/plugin.py`` (entry class)

Интеграция: ``make wizard-plugin``.

Запуск:

    # интерактивный wizard
    python tools/wizards/plugin_wizard.py

    # неинтерактивно (CLI)
    python tools/wizards/plugin_wizard.py --name credit_pipeline --description "Credit pipeline"

    # dry-run preview
    python tools/wizards/plugin_wizard.py --name my_plugin --dry-run
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Annotated, Optional

import questionary
import typer
import yaml
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax

ROOT = Path(__file__).resolve().parents[2]
EXTENSIONS_DIR = ROOT / "extensions"

TRUST_TIER_CHOICES = ("A", "B", "C")
TENANT_AWARE_CHOICES = ["true", "false"]


def _get_core_version() -> str:
    """Прочитать текущую версию ядра из ``pyproject.toml``.

    Round 8 fix: wizard раньше хардкодил ``requires_core = ">=22.0,<23"``,
    не соответствующий реальной semver-схеме ядра (``0.20.0``). Теперь
    читаем ``[project].version`` из ``pyproject.toml`` и формируем
    PEP-440 constraint ``>=X.Y,<X.(Y+1)``.

    Returns:
        Semver-строка вида ``"0.20.0"`` или fallback ``"0.0.0"``
        при невозможности распарсить ``pyproject.toml``.
    """
    pyproject = ROOT / "pyproject.toml"
    if not pyproject.exists():
        return "0.0.0"
    try:
        import tomllib

        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
        version = str(data.get("project", {}).get("version", "0.0.0"))
    except Exception:
        return "0.0.0"
    return version


def _default_requires_core() -> str:
    """Сгенерировать ``requires_core`` constraint под текущую версию ядра.

    Round 8 fix: вместо хардкоженного ``">=22.0,<23"`` строим
    ``">=X.Y,<X.(Y+1)"`` из текущей semver-версии. Если версия
    ``0.20.0``, constraint = ``">=0.20,<0.21"``.
    """
    version = _get_core_version()
    parts = version.split(".")
    if len(parts) >= 2:
        major, minor = parts[0], parts[1]
        try:
            next_minor = int(minor) + 1
            return f">={major}.{minor},<{major}.{next_minor}"
        except ValueError:
            return f">={version},<{version.split('.')[0]}.999"
    return f">={version},<999.0"


console = Console()


def _validate_name(name: str) -> str:
    """Валидация snake_case имени plugin."""
    if not name:
        raise typer.Exit(code=1)
    if "-" in name:
        raise typer.Abort(f"Plugin name must be snake_case (no dashes): {name!r}")
    if not name.replace("_", "").isalnum():
        raise typer.Abort(f"Plugin name must contain only a-z, 0-9, _: {name!r}")
    return name


def _plugin_dir(name: str) -> Path:
    return EXTENSIONS_DIR / name


def _plugin_exists(name: str) -> bool:
    return _plugin_dir(name).exists()


def _build_init(name: str) -> str:
    """Build __init__.py."""
    return f'''\
"""extensions.{name} — plugin package."""
from __future__ import annotations

__all__ = []
'''


def _build_plugin_py(name: str, tenant_aware: bool) -> str:
    """Build plugin.py entry class."""
    class_name = "".join(part.title() for part in name.split("_"))
    return f'''\
"""Plugin entry point for extensions.{name}."""

from __future__ import annotations

from dataclasses import dataclass

from gd_integration_tools.core.plugin_runtime import BasePlugin


@dataclass
class {class_name}Plugin(BasePlugin):
    """Plugin ``{name}`` — generated by wizard-plugin S33 W2."""

    name: str = "{name}"
    version: str = "0.1.0"

    def healthcheck(self) -> bool:
        return True
'''


def _build_toml(
    name: str,
    *,
    description: str,
    tenant_aware: bool,
    trust_tier: str,
    requires_core: str = _default_requires_core(),
) -> str:
    """Build plugin.toml manifest."""
    return f"""\
# V11 plugin manifest — extensions/{name} (S33 W2 wizard)
name = "{name}"
version = "0.1.0"
requires_core = "{requires_core}"
entry_class = "extensions.{name}.plugin.{"".join(p.title() for p in name.split("_"))}Plugin"
tenant_aware = {str(tenant_aware).lower()}
description = "{description}"
trust_tier = "{trust_tier}"

# ─── Runtime capabilities (capability-gate V11.1) ─────────────────
# Каждую capability нужно декларировать явно.
# net.outbound scope: GlobScopeMatcher ('*.example.com'); :external требует WAF.
# db.read/db.write scope: ExactAliasMatcher — имя домена ресурса.
# mq.publish scope: GlobScopeMatcher ('topic.*').

# Примеры (раскомментируйте и адаптируйте):
# [[capabilities]]
# name = "net.outbound"
# scope = "*.example.com"
#
# [[capabilities]]
# name = "db.read"
# scope = "my_resource"
#
# [[capabilities]]
# name = "db.write"
# scope = "my_resource"

# ─── Declarative inventory ───────────────────────────────────────
# Заполните после добавления actions/repositories/processors/sources/sinks/schemas.
[provides]
actions = []
repositories = []
processors = []
sources = []
sinks = []
schemas = []
"""


def _build_yaml(
    name: str, description: str, *, tenant_aware: bool, trust_tier: str
) -> str:
    data = {
        "plugin_id": name,
        "name": name,
        "version": "0.1.0",
        "description": description,
        "trust_tier": trust_tier,
        "tenant_aware": tenant_aware,
        "capabilities": [],
        "provides": {
            "actions": [],
            "repositories": [],
            "processors": [],
            "sources": [],
            "sinks": [],
            "schemas": [],
        },
    }
    return yaml.safe_dump(data, allow_unicode=True, sort_keys=False)


def _preview(
    name: str, description: str, *, tenant_aware: bool, trust_tier: str
) -> None:
    """Print diff preview in rich."""
    toml_content = _build_toml(
        name, description=description, tenant_aware=tenant_aware, trust_tier=trust_tier
    )
    yaml_content = _build_yaml(
        name, description=description, tenant_aware=tenant_aware, trust_tier=trust_tier
    )

    toml_syntax = Syntax(toml_content, "toml", theme="monokai", line_numbers=True)
    yaml_syntax = Syntax(yaml_content, "yaml", theme="monokai", line_numbers=True)

    console.print(
        Panel(toml_syntax, title=f"extensions/{name}/plugin.toml", expand=False)
    )
    console.print(
        Panel(yaml_syntax, title=f"extensions/{name}/manifest.yaml", expand=False)
    )


def _write_scaffold(
    name: str,
    description: str,
    *,
    tenant_aware: bool = True,
    trust_tier: str = "B",
    requires_core: str = _default_requires_core(),
    force: bool = False,
) -> Path:
    """Write plugin.toml + __init__.py + plugin.py. Returns path to directory."""
    target = _plugin_dir(name)
    if target.exists() and not force:
        raise FileExistsError(
            f"Directory already exists: {target}. Use --force to overwrite."
        )
    target.mkdir(parents=True, exist_ok=True)

    (target / "plugin.toml").write_text(
        _build_toml(
            name,
            description=description,
            tenant_aware=tenant_aware,
            trust_tier=trust_tier,
            requires_core=requires_core,
        ),
        encoding="utf-8",
    )
    (target / "__init__.py").write_text(_build_init(name), encoding="utf-8")
    (target / "plugin.py").write_text(
        _build_plugin_py(name, tenant_aware=tenant_aware), encoding="utf-8"
    )
    return target


# ─── Typer app ────────────────────────────────────────────────────────────────

app = typer.Typer(name="wizard-plugin", help=__doc__, add_completion=False)

dry_run_option = typer.Option(
    False, "--dry-run", help="Show diff without writing files"
)
force_option = typer.Option(False, "--force", help="Overwrite existing directory")
extensions_dir_option = typer.Option(
    EXTENSIONS_DIR, "--extensions-dir", help="Extensions directory"
)


@app.command()
def cli(
    ctx: typer.Context,
    name: Annotated[
        Optional[str], typer.Option("--name", help="snake_case plugin name")
    ] = None,
    description: Annotated[
        Optional[str], typer.Option("--description", help="Plugin description")
    ] = None,
    tenant_aware: bool = True,
    trust_tier: str = "B",
    requires_core: str = _default_requires_core(),
    dry_run: bool = dry_run_option,
    force: bool = force_option,
    extensions_dir: Path = extensions_dir_option,
) -> None:
    """Interactive wizard for creating a new plugin scaffold."""

    global EXTENSIONS_DIR
    if extensions_dir and extensions_dir != EXTENSIONS_DIR:
        EXTENSIONS_DIR = extensions_dir

    is_interactive = sys.stdin.isatty() and name is None

    # ── Interactive mode ───────────────────────────────────────────────────
    if is_interactive:
        console.print("[bold cyan]== Plugin Wizard (S33 W2) ==[/bold cyan]")

        name = questionary.text(
            "Plugin name (snake_case, e.g. credit_pipeline):", validate=_validate_name
        ).ask()
        if not name:
            raise typer.Abort()

        if _plugin_exists(name) and not force:
            console.print(
                f"[yellow]Warning: extensions/{name} already exists. Use --force to overwrite.[/yellow]"
            )
            raise typer.Exit(code=0)

        description = (
            questionary.text("Plugin description:", default="My custom plugin").ask()
            or "My custom plugin"
        )

        tenant_aware = questionary.confirm("Tenant-aware plugin?", default=True).ask()

        trust_tier = questionary.select(
            "Trust tier:", choices=list(TRUST_TIER_CHOICES)
        ).ask()

        requires_core = (
            questionary.text(
                "requires_core (core version constraint):",
                default=_default_requires_core(),
            ).ask()
            or _default_requires_core()
        )

        console.print("[bold cyan]== Preview ==[/bold cyan]")
        _preview(name, description, tenant_aware=tenant_aware, trust_tier=trust_tier)

        confirm_write = questionary.confirm("Create files?", default=True).ask()
        if not confirm_write:
            console.print("[yellow]Cancelled.[/yellow]")
            raise typer.Exit(code=0)

        try:
            target = _write_scaffold(
                name,
                description or "My custom plugin",
                tenant_aware=tenant_aware,
                trust_tier=trust_tier,
                requires_core=requires_core,
                force=force,
            )
        except FileExistsError as exc:
            console.print(f"[red]{exc}[/red]")
            raise typer.Exit(code=1)

        console.print(f"[green]OK: Plugin scaffold created at {target}[/green]")
        console.print(f"  -> {target / 'plugin.toml'}")
        console.print(f"  -> {target / '__init__.py'}")
        console.print(f"  -> {target / 'plugin.py'}")
        return

    # ── Non-interactive mode (CLI) ────────────────────────────────────────────
    if not name:
        console.print("[red]Error: --name is required in non-interactive mode[/red]")
        raise typer.Exit(code=1)

    try:
        _validate_name(name)
    except typer.Abort:
        raise

    if _plugin_exists(name) and not force:
        console.print(
            f"[red]Directory extensions/{name} already exists. Use --force.[/red]"
        )
        raise typer.Exit(code=1)

    # ── Dry-run ───────────────────────────────────────────────────────────────
    if dry_run:
        console.print(f"\n[bold]Dry-run: extensions/{name}[/bold]\n")
        _preview(
            name,
            description or "My custom plugin",
            tenant_aware=tenant_aware,
            trust_tier=trust_tier,
        )
        raise typer.Exit(code=0)

    # ── Write files ───────────────────────────────────────────────────────────
    try:
        target = _write_scaffold(
            name,
            description or "My custom plugin",
            tenant_aware=tenant_aware,
            trust_tier=trust_tier,
            requires_core=requires_core,
            force=force,
        )
    except FileExistsError as exc:
        console.print(f"[red]{exc}[/red]")
        raise typer.Exit(code=1)

    console.print(f"[green]OK: Plugin scaffold created at {target}[/green]")
    console.print(f"  -> {target / 'plugin.toml'}")
    console.print(f"  -> {target / '__init__.py'}")
    console.print(f"  -> {target / 'plugin.py'}")


if __name__ == "__main__":
    app()
