apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: gd-integration-tools
    app.kubernetes.io/component: worker
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
    sprint: s30
    wave: k5-w5-helm
spec:
  replicas: {{ .Values.worker.replicas }}
  revisionHistoryLimit: {{ .Values.worker.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: gd-integration-tools
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gd-integration-tools
        app.kubernetes.io/component: worker
        app.kubernetes.io/version: {{ .Values.image.tag | quote }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: 9090
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ .Values.app.serviceAccount.name }}
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
        seccompProfile:
          type: {{ .Values.securityContext.seccompProfileType }}
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
      containers:
        - name: worker
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          envFrom:
            - configMapRef:
                name: gd-app-config
            - secretRef:
                name: gd-app-secrets
          resources:
            requests:
              cpu: {{ .Values.worker.resources.requests.cpu }}
              memory: {{ .Values.worker.resources.requests.memory }}
            limits:
              cpu: {{ .Values.worker.resources.limits.cpu }}
              memory: {{ .Values.worker.resources.limits.memory }}
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "30"]
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: gd-integration-tools
                    app.kubernetes.io/component: worker
                topologyKey: kubernetes.io/hostname
