apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gd-worker-hpa
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: gd-integration-tools
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.worker.name }}
  minReplicas: {{ .Values.hpa.worker.minReplicas }}
  maxReplicas: {{ .Values.hpa.worker.maxReplicas }}
  metrics:
    - type: External
      external:
        metric:
          name: temporal_task_queue_depth
          selector:
            matchLabels:
              task_queue: gd-integration
        target:
          type: AverageValue
          averageValue: {{ .Values.hpa.worker.targetQueueDepth }}
