apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gd-app-pdb
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: gd-integration-tools
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gd-integration-tools
