apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: gd-integration-tools
    app.kubernetes.io/component: app
