apiVersion: v1
kind: Service
metadata:
  name: gd-worker-metrics
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: gd-integration-tools
    app.kubernetes.io/component: worker
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: gd-integration-tools
    app.kubernetes.io/component: worker
